/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type PullQuote = {
  _type: "pullQuote";
  quote: string;
  supportingText?: string;
};

export type ImageGallery = {
  _type: "imageGallery";
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }>;
};

export type TextSection = {
  _type: "textSection";
  label?: string;
  lead?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type JournalPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "journalPage";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: PostReference | CategoryReference | JournalPageReference;
  language: string;
};

export type JournalPage = {
  _id: string;
  _type: "journalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  eyebrow: string;
  heading: string;
  seo?: Seo;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title: string;
  slug: Slug;
  category: CategoryReference;
  excerpt: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  featured?: boolean;
  publishedAt: string;
  marqueeText?: string;
  body: Array<
    | ({
        _key: string;
      } & TextSection)
    | ({
        _key: string;
      } & ImageGallery)
    | ({
        _key: string;
      } & PullQuote)
  >;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title: string;
  slug: Slug;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | PullQuote
  | ImageGallery
  | TextSection
  | TranslationMetadata
  | InternationalizedArrayReference
  | PostReference
  | CategoryReference
  | JournalPageReference
  | InternationalizedArrayReferenceValue
  | JournalPage
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Category
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: JOURNAL_PAGE_QUERY
// Query: *[_type == "journalPage" && language == $locale][0] {    _id,    _type,    language,    eyebrow,    heading,    seo {      title,      description,      ogImage {        asset->{          _id,          url,          metadata {            lqip,            dimensions { width, height }          }        },        alt,        hotspot,        crop      }    }  }
export type JOURNAL_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "journalPage";
  language: string | null;
  eyebrow: string;
  heading: string;
  seo: {
    title: string | null;
    description: string | null;
    ogImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && language == $locale] | order(order asc, title asc) {    _id,    _type,    language,    title,    "slug": slug.current,    order  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  _type: "category";
  language: string | null;
  title: string;
  slug: string;
  order: number | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && language == $locale && defined(slug.current)] | order(publishedAt desc) {    _id,    _type,    language,    title,    "slug": slug.current,    excerpt,    featured,    publishedAt,    category->{      _id,      title,      "slug": slug.current    },    coverImage {      asset->{        _id,        url,        metadata {          lqip,          dimensions { width, height, aspectRatio }        }      },      alt,      hotspot,      crop    }  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "post";
  language: string | null;
  title: string;
  slug: string;
  excerpt: string;
  featured: boolean | null;
  publishedAt: string;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
}>;

// Source: sanity/lib/queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug && language == $locale][0] {    _id,    _type,    language,    title,    "slug": slug.current,    excerpt,    featured,    publishedAt,    marqueeText,    category->{      _id,      title,      "slug": slug.current    },    coverImage {      asset->{        _id,        url,        metadata {          lqip,          dimensions { width, height, aspectRatio }        }      },      alt,      hotspot,      crop    },    body[] {      _key,      _type,      _type == "textSection" => {        label,        lead,        body      },      _type == "imageGallery" => {        images[] {          _key,          asset->{            _id,            url,            metadata {              lqip,              dimensions { width, height, aspectRatio }            }          },          alt,          hotspot,          crop        }      },      _type == "pullQuote" => {        quote,        supportingText      }    },    seo {      title,      description,      ogImage {        asset->{          _id,          url,          metadata {            lqip,            dimensions { width, height }          }        },        alt,        hotspot,        crop      }    },    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[] {      "locale": _key,      "slug": value->slug.current    }  }
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "post";
  language: string | null;
  title: string;
  slug: string;
  excerpt: string;
  featured: boolean | null;
  publishedAt: string;
  marqueeText: string | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  body: Array<
    | {
        _key: string;
        _type: "imageGallery";
        images: Array<{
          _key: string;
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
                aspectRatio: number;
              } | null;
            } | null;
          } | null;
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        }>;
      }
    | {
        _key: string;
        _type: "pullQuote";
        quote: string;
        supportingText: string | null;
      }
    | {
        _key: string;
        _type: "textSection";
        label: string | null;
        lead: string | null;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "h2" | "h3" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
      }
  >;
  seo: {
    title: string | null;
    description: string | null;
    ogImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  } | null;
  translations: Array<{
    locale: string;
    slug: string | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: POST_SLUGS_BY_LOCALE_QUERY
// Query: *[_type == "post" && defined(slug.current)] {    language,    "slug": slug.current  }
export type POST_SLUGS_BY_LOCALE_QUERY_RESULT = Array<{
  language: string | null;
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: ALL_POSTS_SITEMAP_QUERY
// Query: *[_type == "post" && defined(slug.current)] {    _id,    language,    "slug": slug.current,    _updatedAt,    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[] {      "locale": _key,      "slug": value->slug.current    }  }
export type ALL_POSTS_SITEMAP_QUERY_RESULT = Array<{
  _id: string;
  language: string | null;
  slug: string;
  _updatedAt: string;
  translations: Array<{
    locale: string;
    slug: string | null;
  }> | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "journalPage" && language == $locale][0] {\n    _id,\n    _type,\n    language,\n    eyebrow,\n    heading,\n    seo {\n      title,\n      description,\n      ogImage {\n        asset->{\n          _id,\n          url,\n          metadata {\n            lqip,\n            dimensions { width, height }\n          }\n        },\n        alt,\n        hotspot,\n        crop\n      }\n    }\n  }\n': JOURNAL_PAGE_QUERY_RESULT;
    '\n  *[_type == "category" && language == $locale] | order(order asc, title asc) {\n    _id,\n    _type,\n    language,\n    title,\n    "slug": slug.current,\n    order\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "post" && language == $locale && defined(slug.current)] | order(publishedAt desc) {\n    _id,\n    _type,\n    language,\n    title,\n    "slug": slug.current,\n    excerpt,\n    featured,\n    publishedAt,\n    category->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    coverImage {\n      asset->{\n        _id,\n        url,\n        metadata {\n          lqip,\n          dimensions { width, height, aspectRatio }\n        }\n      },\n      alt,\n      hotspot,\n      crop\n    }\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug && language == $locale][0] {\n    _id,\n    _type,\n    language,\n    title,\n    "slug": slug.current,\n    excerpt,\n    featured,\n    publishedAt,\n    marqueeText,\n    category->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    coverImage {\n      asset->{\n        _id,\n        url,\n        metadata {\n          lqip,\n          dimensions { width, height, aspectRatio }\n        }\n      },\n      alt,\n      hotspot,\n      crop\n    },\n    body[] {\n      _key,\n      _type,\n      _type == "textSection" => {\n        label,\n        lead,\n        body\n      },\n      _type == "imageGallery" => {\n        images[] {\n          _key,\n          asset->{\n            _id,\n            url,\n            metadata {\n              lqip,\n              dimensions { width, height, aspectRatio }\n            }\n          },\n          alt,\n          hotspot,\n          crop\n        }\n      },\n      _type == "pullQuote" => {\n        quote,\n        supportingText\n      }\n    },\n    seo {\n      title,\n      description,\n      ogImage {\n        asset->{\n          _id,\n          url,\n          metadata {\n            lqip,\n            dimensions { width, height }\n          }\n        },\n        alt,\n        hotspot,\n        crop\n      }\n    },\n    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[] {\n      "locale": _key,\n      "slug": value->slug.current\n    }\n  }\n': POST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)] {\n    language,\n    "slug": slug.current\n  }\n': POST_SLUGS_BY_LOCALE_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)] {\n    _id,\n    language,\n    "slug": slug.current,\n    _updatedAt,\n    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[] {\n      "locale": _key,\n      "slug": value->slug.current\n    }\n  }\n': ALL_POSTS_SITEMAP_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
